//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rasta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ipexopex
    {
        public int IPEXOPEXID { get; set; }
        public string IPEXOPEXName { get; set; }
        public string ReferenceType { get; set; }
        public string Header { get; set; }
    }
}
