//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rasta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_supplier
    {
        public int SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string SupplierCode { get; set; }
        public Nullable<int> BankID { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public Nullable<int> SupplierTypeID { get; set; }
    }
}
