//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rasta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_apitexpense
    {
        public int APITExpenseID { get; set; }
        public Nullable<int> APID { get; set; }
        public Nullable<int> RebillID { get; set; }
        public Nullable<int> CBSID { get; set; }
        public Nullable<int> IPEXOPEXID { get; set; }
    }
}
