//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rasta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_project
    {
        public int ProjectID { get; set; }
        public Nullable<int> ProjectTypeID { get; set; }
        public Nullable<double> AmountTillDate { get; set; }
        public Nullable<double> RemainingAmount { get; set; }
        public Nullable<double> TotalAmount { get; set; }
        public string ProjctName { get; set; }
    }
}
