//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rasta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_accountreceivable
    {
        public int InvoiceID { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> ExpenseTypeID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> isForecast { get; set; }
        public Nullable<int> credittobank { get; set; }
    }
}
