//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rasta.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_bank
    {
        public int BankID { get; set; }
        public string BankName { get; set; }
        public string BankCode { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string SwiftCode { get; set; }
        public string IBAN { get; set; }
        public string Country { get; set; }
        public Nullable<int> DisciplineID { get; set; }
        public Nullable<double> cash { get; set; }
        public Nullable<double> NegativeCash { get; set; }
    }
}
